#!/usr/bin/env bash
# Deploys Persia Panel application code (backend + frontend) on top of the
# OS packages prepared by install.sh. Run this from inside the cloned repo
# (any location on disk), as root:
#
#   sudo bash installer/deploy.sh
#
# Idempotent: safe to re-run after a `git pull` to ship an update — existing
# secrets in backend/.env are preserved, not regenerated.
#
# Optional env vars:
#   PANEL_HOST   - hostname/IP the panel UI will be reached at (used for the
#                  self-signed cert CN and the frontend's baked-in API URL).
#                  If unset, you'll be prompted (or it falls back to the
#                  server's auto-detected public IP in non-interactive runs).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/lib/network.sh"

PANEL_USER="persiapanel"
DB_NAME="persiapanel"
DB_USER="persiapanel"

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    log_error "Run this script as root (sudo bash installer/deploy.sh)"
    exit 1
  fi
}

random_secret() {
  openssl rand -hex 24
}

resolve_panel_host() {
  if [[ -n "${PANEL_HOST:-}" ]]; then
    echo "${PANEL_HOST}"
    return
  fi
  if [[ -t 0 ]]; then
    local input
    read -rp "Hostname or IP the panel will be reached at [auto-detect]: " input || true
    if [[ -n "${input}" ]]; then
      echo "${input}"
      return
    fi
  fi
  detect_public_ip || echo "127.0.0.1"
}

setup_database() {
  log_info "Configuring PostgreSQL role/database"
  if ! command -v psql >/dev/null; then
    log_error "psql not found — run installer/install.sh first"
    exit 1
  fi

  if [[ -f "${REPO_DIR}/backend/.env" ]]; then
    log_ok "backend/.env already exists — reusing existing DB credentials"
    return
  fi

  DB_PASSWORD="$(random_secret)"
  sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 \
    || sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';" >/dev/null
  sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
    || sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" >/dev/null
}

write_backend_env() {
  if [[ -f "${REPO_DIR}/backend/.env" ]]; then
    return
  fi
  log_info "Generating backend/.env"
  ADMIN_PASSWORD="$(openssl rand -base64 18)"
  cp "${REPO_DIR}/backend/.env.example" "${REPO_DIR}/backend/.env"
  {
    echo ""
    echo "# --- Generated by installer/deploy.sh on $(date -u +%FT%TZ) ---"
    echo "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
  } >> "${REPO_DIR}/backend/.env"

  # Patch in the real DB URL and a fresh JWT secret (sed -i without a
  # extension arg differs between GNU/BSD sed; the installer targets Ubuntu
  # so GNU sed's `-i` with no suffix is correct here).
  sed -i "s#^DATABASE_URL=.*#DATABASE_URL=\"postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}\"#" "${REPO_DIR}/backend/.env"
  sed -i "s#^JWT_SECRET=.*#JWT_SECRET=\"$(random_secret)\"#" "${REPO_DIR}/backend/.env"

  chmod 600 "${REPO_DIR}/backend/.env"
  log_ok "backend/.env created (DB password + JWT secret generated, mode 600)"
}

build_backend() {
  log_info "Installing backend dependencies and building"
  (cd "${REPO_DIR}/backend" && npm ci --no-audit --no-fund && npx prisma generate && npm run build)

  log_info "Running database migrations"
  (cd "${REPO_DIR}/backend" && npx prisma migrate deploy)

  log_info "Seeding admin account (skipped if one already exists)"
  (cd "${REPO_DIR}/backend" && set -a && source .env && set +a && npx ts-node prisma/seed.ts) \
    || log_warn "Admin seed step failed — check backend/.env's ADMIN_* values and run manually: cd backend && npx ts-node prisma/seed.ts"
}

build_frontend() {
  local panel_host="$1"
  log_info "Installing frontend dependencies and building (API URL: https://${panel_host}:2087/api)"
  echo "NEXT_PUBLIC_API_URL=https://${panel_host}:2087/api" > "${REPO_DIR}/frontend/.env.local"
  (cd "${REPO_DIR}/frontend" && npm ci --no-audit --no-fund && npm run build)
}

install_systemd_units() {
  log_info "Installing systemd units for backend and frontend"

  cat > /etc/systemd/system/persia-panel-backend.service <<EOF
[Unit]
Description=Persia Panel backend API
After=network.target postgresql.service

[Service]
Type=simple
WorkingDirectory=${REPO_DIR}/backend
EnvironmentFile=${REPO_DIR}/backend/.env
ExecStart=/usr/bin/node dist/main.js
Restart=on-failure
RestartSec=3
# Root is required: this process directly shells out to rndc, named-checkzone,
# postmap, doveadm, systemctl reload {nginx,postfix,dovecot}, useradd, chown,
# ufw, etc. across the whole panel (nginx/php/db/dns/mail/backups/security
# modules) — there is no sudoers/capability allowlist in front of it (yet).
User=root

[Install]
WantedBy=multi-user.target
EOF

  cat > /etc/systemd/system/persia-panel-frontend.service <<EOF
[Unit]
Description=Persia Panel frontend (Next.js)
After=network.target persia-panel-backend.service

[Service]
Type=simple
WorkingDirectory=${REPO_DIR}/frontend
ExecStart=/usr/bin/npx next start -p 3001 -H 127.0.0.1
Restart=on-failure
RestartSec=3
User=${PANEL_USER}

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now persia-panel-backend >/dev/null 2>&1 || log_warn "Could not enable/start persia-panel-backend"
  systemctl enable --now persia-panel-frontend >/dev/null 2>&1 || log_warn "Could not enable/start persia-panel-frontend"
}

configure_panel_nginx() {
  local panel_host="$1"
  log_info "Configuring nginx reverse proxy for the panel UI (port 2087)"

  mkdir -p /etc/nginx/ssl/panel
  if [[ ! -f /etc/nginx/ssl/panel/panel.crt ]]; then
    log_info "Generating a self-signed TLS certificate for the panel UI (replace with a real one later via the SSL section once a domain points here)"
    openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
      -keyout /etc/nginx/ssl/panel/panel.key \
      -out /etc/nginx/ssl/panel/panel.crt \
      -subj "/CN=${panel_host}" >/dev/null 2>&1
  fi

  cat > /etc/nginx/sites-available/persia-panel-ui <<EOF
# Managed by Persia Panel deploy script — this is the panel's OWN admin UI,
# distinct from customer-hosted site vhosts (those are written separately
# into this same sites-available/sites-enabled directory at runtime by
# backend/src/system/nginx/nginx.service.ts).
server {
    listen 2087 ssl;
    listen [::]:2087 ssl;
    server_name ${panel_host};

    ssl_certificate     /etc/nginx/ssl/panel/panel.crt;
    ssl_certificate_key /etc/nginx/ssl/panel/panel.key;

    location /api/ {
        rewrite ^/api/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

  ln -sf /etc/nginx/sites-available/persia-panel-ui /etc/nginx/sites-enabled/persia-panel-ui
  nginx -t && systemctl reload nginx
}

main() {
  require_root

  if [[ ! -f "${REPO_DIR}/backend/package.json" || ! -f "${REPO_DIR}/frontend/package.json" ]]; then
    log_error "Could not find backend/ and frontend/ next to installer/ — run this from inside the cloned repo"
    exit 1
  fi

  local panel_host
  panel_host="$(resolve_panel_host)"
  log_info "Deploying Persia Panel — panel host: ${panel_host}"

  setup_database
  write_backend_env
  build_backend
  build_frontend "${panel_host}"
  install_systemd_units
  configure_panel_nginx "${panel_host}"

  log_ok "Deployment complete."
  log_ok "Panel UI: https://${panel_host}:2087  (self-signed certificate — your browser will warn once)"
  if grep -q "^# --- Generated by installer/deploy.sh" "${REPO_DIR}/backend/.env" 2>/dev/null; then
    local admin_user admin_pass
    admin_user="$(grep '^ADMIN_USERNAME=' "${REPO_DIR}/backend/.env" | cut -d= -f2- || echo admin)"
    admin_pass="$(grep '^ADMIN_PASSWORD=' "${REPO_DIR}/backend/.env" | cut -d= -f2-)"
    log_ok "First login — username: ${admin_user:-admin}  password: ${admin_pass}"
    log_warn "This password is only shown once here and stored in backend/.env — save it now."
  fi
}

main "$@"
